name: chat_app_project
description: Posts App clean with architecture


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  # Bloc for state management
  flutter_bloc:
  # Functional programming things
  dartz:
  # Value equality
  equatable:
  # Service locator
  get_it:
  # Remote API
  internet_connection_checker:
  http:
  # Local cache
  shared_preferences:
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true


